[package]
name = "rust_in_action"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cpu"
path = "src/cpu/main.rs"

#[[bin]]
#name = "hexdump"
#path = "src/hexdump/src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
